---
title: "District Broomball"
author: "Stats Department"
date: "`r format(Sys.time(), '%B %d, %Y')`"
params:
  db: "stats.sdb"
---

```{r setup, include=F}
library(tidyverse)
source("stats.R")
knitr::opts_chunk$set(echo = F)
```

### Season

```{r}
list.files(pattern = "*.html$") %>%
  enframe(name = NULL, value = "path") %>%
  arrange(path) %>%
  filter(str_detect(path, "^\\d+-[\\d\\.]+.html$")) %>%
  separate(path, c("year", "season"), sep = "[-.]", extra = "drop", remove = F) %>%
  mutate(
    path = paste0("[link](", path, ")"),
    season = recode(season, !!!iso_season)
  ) %>%
  group_by(year, season) %>%
  summarise(path = paste(path, collapse = " | "), .groups = "drop") %>%
  pivot_wider(names_from = season, values_from = path) %>%
  select(year, Spring, Summer, Autumn, Winter) %>%
  knitr::kable()
```

### Career

[Career Stats](career.html)

### CSV

```{r, csv}
conn <- DBI::dbConnect(RSQLite::SQLite(), "stats.sdb")

df.lstat <- DBI::dbReadTable(conn, "lstat") %>% write_csv("lstat.csv")

res <- DBI::dbSendQuery(conn, "SELECT * FROM point as x JOIN match as y ON x.match = y.id;")
df.point <- DBI::dbFetch(res) %>% write_csv("point.csv")
DBI::dbClearResult(res)

res <- DBI::dbSendQuery(conn, "SELECT * FROM shot as x JOIN match as y ON x.match = y.id;")
DBI::dbFetch(res) %>% write_csv("shot.csv")
DBI::dbClearResult(res)

DBI::dbDisconnect(conn)
```

- [Legacy](lstat.csv)
- [Point](point.csv)
- [Shot](shot.csv)

### Database

- [SQLite Database](stats.sdb)
- [ER Model](stats.mwb)
- [Excel Template](template.xlsx)

### Acknowledgements

Thanks to everyone for recording stats during clock duty and to Paul Fajman for maintaining the first stats database!
