---
title: "Season"
author: "Stats Department"
date: "`r format(Sys.time(), '%B %d, %Y')`"
params:
  db: "stats.sdb"
  year: 2020
  season: 24
  out: NULL
---

```{r, setup, include=F}
library(tidyverse)
library(visNetwork)
source("stats.R")
knitr::opts_chunk$set(echo = F, fig.width = 10)
```

## Stats: `r unname(iso_season[as.character(params$season)])`, `r params$year`

```{r query}
con <- DBI::dbConnect(RSQLite::SQLite(), params$db)

sql <- "
  SELECT * FROM roster as x JOIN team as y ON x.team = y.id AND x.team IN (
    SELECT team1 FROM match WHERE year = ? AND season = ? UNION ALL 
    SELECT team2 FROM match WHERE year = ? AND season = ?
  );
"
res <- DBI::dbSendQuery(con, sql, param = list(params$year, params$season, params$year, params$season))
df.roster <- DBI::dbFetch(res)
DBI::dbClearResult(res)

df.color <- distinct(df.roster, team, color)

res <- 
  DBI::dbSendQuery(
    con, "SELECT * FROM point as x JOIN match as y ON x.match = y.id WHERE year = ? AND season = ?;", 
    param = list(params$year, params$season)
  )
df.point <- DBI::dbFetch(res)
df.match <- distinct(df.point, week, game, team1, team2)
df.point <- select(df.point, week, game, 3:13)
DBI::dbClearResult(res)

res <- 
  DBI::dbSendQuery(
    con, "SELECT * FROM penalty as x JOIN match as y ON x.match = y.id WHERE year = ? AND season = ?;", 
    param = list(params$year, params$season)
  )
df.penalty <- DBI::dbFetch(res) %>% select(week, game, 3:11)
DBI::dbClearResult(res)

res <- 
  DBI::dbSendQuery(
    con, "SELECT * FROM shot as x JOIN match as y ON x.match = y.id WHERE year = ? AND season = ?;", 
    param = list(params$year, params$season)
  )
df.shot <- DBI::dbFetch(res) %>% select(week, game, 3:11)
DBI::dbClearResult(res)

DBI::dbDisconnect(con)
```

### Results

```{r}
df.score <- count(df.point, week, game, team) %>% arrange(week, game)
df.score <-
  bind_cols(
    select(merge(df.match, df.score, by.x = c("week", "game", "team1"), by.y = c("week", "game", "team"), all.x = T), -team2),
    select(merge(df.match, df.score, by.x = c("week", "game", "team2"), by.y = c("week", "game", "team"), all.x = T), -team1)
  ) %>%
  merge(df.color, by.x = "team1", by.y = "team") %>%
  merge(df.color, by.x = "team2", by.y = "team", suffixes = c("", "2")) %>%
  replace(is.na(.), 0) %>%
  setNames(c("team2", "team1", "week", "game", "n1", "week1", "game1", "n2", "color1", "color2")) %>%
  arrange(week, game) %>%
  select(week, game, team1, color1, n1, n2, color2, team2, -week1, -game1)

datatableize(df.score)
```

### Standing

```{r}
df.standing <-
  mutate(
    df.score, 
    r1 = if_else(n1 == n2, "T", ifelse(n1 < n2, "L", "W")),
    r2 = if_else(n1 == n2, "T", ifelse(n2 < n1, "L", "W"))
  )
bind_rows(
  rename(count(df.standing, team1, r1), team = team1, r = r1),
  rename(count(df.standing, team2, r2), team = team2, r = r2)
) %>%
  group_by(team, r) %>%
  summarise(n = sum(n)) %>%
  ungroup() %>%
  spread(r, n) %>%
  bind_rows(data.frame(team = character(), W = integer(), `T` = integer(), L = integer(), stringsAsFactors = F)) %>%
  replace(is.na(.), 0) %>%
  merge(df.color, sort = F) %>%
  select(team, color, W, `T`, L) %>%
  arrange(L, desc(`T`), desc(W)) %>%
  datatableize()
```

### Career (Season)

```{r, career}
overall.2(df.point, df.penalty) %>% 
  mutate(A1 = EVA1 + PPA1 + SHA1, A2 = EVA2 + PPA2 + SHA2) %>%
  merge(select(df.roster, team, player, color), sort = F) %>%
  select(player, team, color, P, G, A, A1, A2, PEN, PIM) %>%
  arrange(desc(P)) %>%
  datatableize()
```

### Goalie

```{r, goalie}
x <- 
  group_by(df.shot, week, game, period, goalie) %>% 
  summarise_at("SH", sum) %>% 
  ungroup()

y <-
  filter(df.point, EN == 0 & !is.na(goalie)) %>% 
  count(week, game, period, goalie, name = "GA")

z <- 
  merge(x, y, by = c("week", "game", "period", "goalie"), suffixes = c("", ".y"), all.x = T, sort = F) %>%
  replace(is.na(.), 0) %>%
  mutate(`SV%` = sprintf("%0.2f%%", (SH - GA) / SH * 100))

x <- spread(select(z, -GA, -`SV%`), period, SH) %>% mutate(total = rowSums(.[4:ncol(.)]))
y <- spread(select(z, -SH, -`SV%`), period, GA) %>% mutate(total = rowSums(.[4:ncol(.)]))
z <- spread(select(z, -GA, -SH), period, `SV%`) %>% mutate(total = sprintf("%0.2f%%", (x$total - y$total) / x$total * 100))

nx <- ncol(x) - 3 - 1
ny <- ncol(y) - 3 - 1
nz <- ncol(z) - 3 - 1
y <- y[4:ncol(y)]
z <- z[4:ncol(z)]

df.goalie <- 
  bind_cols(x, y, z) %>%
  merge(select(df.roster, team, player, color), all.x = T, by.x = "goalie", by.y = "player", sort = F) %>%
  select(goalie, team, color, week, game, everything())

DT::datatable(
  df.goalie,
  style = "bootstrap",
  class = "table-bordered table-striped table-hover responsive",
  filter = list(position = "top"),
  rownames = F,
  container = htmltools::withTags(
    table(
      class = "display",
      thead(
        tr(
          th(rowspan = 2, "goalie"),
          th(rowspan = 2, "team"),
          th(rowspan = 2, "color"),
          th(rowspan = 2, "week"),
          th(rowspan = 2, "game"),
          th(colspan = nx + 1, "SH"),
          th(colspan = ny + 1, "GA"),
          th(colspan = nz + 1, "SV%")
        ),
        tr(lapply(c(1:nx, "∑", 1:ny, "∑", 1:nz, "∑"), th))
      )
    )
  )
)
```

### Assist Network

```{r assist_network}
df.edges <-
  bind_rows(
    mutate(rename(select(df.point, assist1, shooter), from = assist1, to = shooter), type = "A1") %>%
      mutate(from = if_else(is.na(from), to, from)) %>%
      mutate(type = if_else(from == to, "A0", type)),
    drop_na(mutate(rename(select(df.point, assist2, assist1), from = assist2, to = assist1), type = "A2"), from)
  ) %>%
  rownames_to_column("label") %>%
  mutate(
    type = if_else(is.na(from) & type == "A1", "A0", type), 
    dashes = type == "A2",
    width = 2
  )

df.nodes <- 
  data.frame(id = unique(sort(c(pull(df.edges, from), pull(df.edges, to))))) %>%
  mutate(label = id) %>%
  merge(df.roster, by.x = "id", by.y = "player", all.x = T, sort = F)

visNetwork(df.nodes, df.edges, background = "lightgrey") %>%
  visEdges(arrows = list(to = list(enabled = T)))
```

### Assist Table

```{r, assist_table}
datatableize(df.point)
```

### Penalty

```{r, penalty}
datatableize(df.penalty)
```

### Roster

```{r}
datatableize(df.roster)
```

